name: Build and deploy Node.js app to Azure Web App - CTS-VibeAppso5401-3
 
on:
  push:
    branches:
      - main
  workflow_dispatch:
 
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
 
    steps:
      - uses: actions/checkout@v4
 
      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'
 
      # Install and build frontend
      - name: Install and build frontend
        run: |
          cd client
          npm install
          npm run build
 
      # Install backend dependencies
      - name: Install backend dependencies
        run: |
          cd server
          npm install
 
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: .
 
  deploy:
    runs-on: ubuntu-latest
    needs: build
 
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app
 
      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'CTS-VibeAppce21203-2'  # <-- Make sure this matches your Azure Web App name
          slot-name: 'Production'
          package: .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE}}
